blank_issues_enabled: false
contact_links:
  - name: Bayat
    url: https://bayat.io
    about: Learn more about Bayat and find new ways to reach out
  - name: Forums
    url: https://forums.bayat.io
    about: Discuss about Bayat services and products
  - name: Discord
    url: https://discord.gg/X2Ag9gC2zT
    about: Join our Discord community!
